import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Chef est un retardateur',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <meta charSet="utf-8" />
      <meta name="viewport" content="Je suis en retard, je souhaite obtenir une liste de références de restaurants pour passer une commande de repas." />
      <body className={inter.className}>{children}</body>
    </html>
  )
}